### ISSUE TITLE
Image upload broken

### ISSUE THREAD

**Issue by carlescufi** [apache/mynewt-mcumgr-cli#2] opened 2018-07-03 12:07 UTC
Running `mcumgr` on Windows with the following settings:

```
C:\Users\Carles\go\bin>mcumgr conn show com3
Connection profiles:
  com3: type=serial, connstring='dev=COM3,baud=115200'
```

Every time I try to send an image to MCUboot in recovery mode:

```
C:\Users\Carles\go\bin>mcumgr image upload c:\Users\Carles\shared\signed_smp_svr_12_06_2018_8h30m.bin -c com3 -e
 0 / 110780 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%
Error: 3
```

**Comment by carlescufi** [comment] 2018-07-03 12:07
CC @ccollins476ad @utzig @sjanc @lemrey

**Comment by carlescufi** [comment] 2018-07-03 12:08
I wonder what `Error: 3` means?

**Comment by carlescufi** [comment] 2018-07-03 12:10
@ccollins476ad I would report the exact mcumgr version, but it simply shows:

```
C:\Users\Carles\go\bin>mcumgr version
mcumgr 0.0.0-dev
```

I ran ` go get -u github.com/apache/mynewt-mcumgr-cli/mcumgr` before testing

**Comment by utzig** [comment] 2018-07-03 12:17
@carlescufi I would bet on `MGMT_ERR_EINVAL`! Could be helpful enabling debug log as well: 

`$ mcumgr image upload c:\Users\Carles\shared\signed_smp_svr_12_06_2018_8h30m.bin -c com3 -e -ldebug`

**Comment by carlescufi** [comment] 2018-07-03 12:25
@utzig thanks! I now realize I get this error on Linux as well after updating `mcumgr`, so this is not a Windows issue. Here's the log:

[log.txt](https://github.com/apache/mynewt-mcumgr-cli/files/2159232/log.txt)

**Comment by carlescufi** [comment] 2018-07-03 15:25
Not sure if this is an MCUmgr or MCUboot issue actually. For now I will keep it here, but there is something definitely broken. @sjanc could you also test for me with MCUboot built with Zephyr and the latest MCUboot that you get with `go get`?

**Comment by ccollins476ad** [comment] 2018-07-03 15:32
I believe this is an issue that was recently introduced into newtmgr (and therefore mcumgr-cli).  The problem is that the CLI tool recently starting including a 32-byte hash in the first upload chunk.  On systems with a limited maximum ATT MTU, this doesn't leave enough room for a "complete" set of image data in the request.  The first request of an upgrade is required to have at least 32 bytes of image data to be valid (it must contain the full image header).

There is a PR that fixes this issue that is ready to be merged: https://github.com/apache/mynewt-newtmgr/pull/92

**Comment by carlescufi** [comment] 2018-07-03 15:42
@ccollins476ad thanks for the info. We'll wait until that PR is merged to close this.

**Comment by carlescufi** [comment] 2018-07-03 16:00
@ccollins476ad btw, is the update propagated automatically to the codebase one gets with `go get` once the PR is merged, or do you need to release a new version of mcumgr?

**Comment by ccollins476ad** [comment] 2018-07-03 18:16
The fix to newtmgr will be automatically included in mcumgr.  By the way, the fix was just merged to the newtmgr repo.

**Comment by carlescufi** [comment] 2018-07-04 07:36
CC @andrzej-kaczmarek

**Comment by carlescufi** [comment] 2018-07-04 07:37
The PR above ( apache/mynewt-newtmgr#92) does not fix this.

Latest log with today's mcumgr: 
[log.txt](https://github.com/apache/mynewt-mcumgr-cli/files/2162238/log.txt)

**Closed as completed** 2018-07-04 10:06 UTC
